version: '3.8'
volumes:
    mysql_db: {}
services:
  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - '8002:80'
  mysql:
    # M1 Macであれば下記のコメントアウトを外す
    # platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - mysql_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '12345678'
    ports:
      - 3306:3306
  httpd:
    build: .
    volumes:
      - ./htdocs:/var/www/html
    ports:
      - '8001:80'
